name: 编译应用

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21

      - name: Grant Gradle execution permission
        run: chmod +x ./gradlew

      - name: Build APK (Release)
        run: ./gradlew assembleRelease

      - name: Upload APK to GitHub Releases
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
